version: "3.8"
services:
  db:
    image: postgres:15
    container_name: auth_db
    command: -p 5435
    expose:
      - 5435
    volumes:
      - db_data:/var/lib/postgresql/data/
    env_file:
      - .env-prod

  app:
    build:
      context: .
    container_name: auth_app
    command: ["/auth_app/start.sh"]
    ports:
      - 8080:8000
    volumes:
      - ./:/auth_app
    depends_on:
      - db
    env_file:
      - .env-prod

volumes:
  db_data:
